name: dashboard_financeiro
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  # Gerenciamento de Estado (BLoC)
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Gráficos
  fl_chart: ^0.68.0

  # Banco de Dados Local
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3

  # Cliente GraphQL para Hasura
  graphql_flutter: ^5.2.0-beta.6

  # Utilitários
  intl: ^0.19.0 # Para formatação de data e moeda

  # Funcionalidade de Exportação
  csv: ^6.0.0
  file_picker: ^8.0.3 # Para salvar o arquivo exportado
  permission_handler: ^11.3.1 # Para permissões de armazenamento

 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter: 
  uses-material-design: true


